{% set name = "weaviate-client" %}
{% set version = "4.19.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/weaviate_client-{{ version }}.tar.gz
  sha256: 99e76e912c95762436089cd5feedbfeea31e892aa13b6ad94729a2a54b316c45

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65
    - setuptools-scm >6.2
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.26.0,<0.29.0
    - validators >=0.34.0,<1.0.0
    - authlib >=1.6.5,<2.0.0
    - pydantic >=2.12.0,<3.0.0
    - grpcio >=1.59.5,<1.80.0
    - deprecation >=2.1.0,<3.0.0
    - protobuf >=4.21.6,<7.0.0

test:
  imports:
    - weaviate
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/weaviate/weaviate-python-client
  summary: A python native Weaviate client
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/weaviate/weaviate-python-client
  doc_url: https://weaviate.io/developers/weaviate/client-libraries/python

extra:
  recipe-maintainers:
    - xylar
